### ISSUE TITLE
[战斗]第10关的Boss好像过了3次

### ISSUE THREAD

**Issue by chenbiao823** [GoodGameStudio/bzdxr#10]
第一次过了以后我暂时退出，再进去发现还得打一次，打过第二次之后过了一会发现Boss战的按键还在，并且关卡仍停留在10，不过第三次过了之后进度就正常前进了。请检查一下，应该不会有什么大问题。

**Comment by dracoplay** [comment]
是bug, 偶尔会出现, 我也发现了, 正在调试

**Comment by dracoplay** [comment]
已修复
