### ISSUE TITLE
[属性]暴击伤害

### ISSUE THREAD

**Issue by chenbiao823** [GoodGameStudio/bzdxr#14]
还没有玩到有暴击属性的进度。不过暴击伤害只增加1%会不会太少了？一般暴击都是普通攻击的一倍吧？

**Comment by dracoplay** [comment]
起始值是1% 后面会有增加暴击伤害的技能 可以把起始值改成100%

**Comment by chenbiao823** [comment]
恩好的，建议改高点，这样玩家更有升级的兴趣

**Comment by dracoplay** [comment]
已把起始值改为100%
