### ISSUE TITLE
[属性]主动攻击的成长和被动攻击差距有点大

### ISSUE THREAD

**Issue by chenbiao823** [GoodGameStudio/bzdxr#16]
目前到高级阶段感觉提升主动攻击的意义不大，建议提高每级成长

**Comment by dracoplay** [comment]
基本上每个被动攻击都有一个辅助技能可以提高主动攻击100%的攻击力, 需要两者结合才能发挥最大威力. 这也是体现玩家水平的地方

**Comment by chenbiao823** [comment]
是说每个技能下面的小书吗？

**Comment by dracoplay** [comment]
对

**Comment by chenbiao823** [comment]
这就涉及到是另一个问题了，玩家不知道小书是干嘛的，还是建议加一些提示吧（比如在主屏幕以类似弹幕的形式划过一些游戏技巧或提示）。玩家的耐心很珍贵，方便他们了解游戏升级的技巧有助于延长玩家游戏时间。

**Comment by dracoplay** [comment]
已在技能描述里加入了各种游戏提示
