### ISSUE TITLE
[界面]点击升级技能的界面后玩家金币显示被挡住了

### ISSUE THREAD

**Issue by chenbiao823** [GoodGameStudio/bzdxr#2]
建议改善UI，让玩家点开的同时也能看到自己目前的金币数量。

**Comment by dracoplay** [comment]
这个要改的话需要把整个ui都调整了比较麻烦 比较简单的解决方案是把金币放到右边 选关放到左边 我试一下效果

**Comment by chenbiao823** [comment]
OK，这个不影响游戏进行。不过方便玩家可能更好吧。

**Comment by dracoplay** [comment]
改成 把金币放到右边 选关放到左边

**Comment by dracoplay** [comment]
label也由你来处理

**Comment by chenbiao823** [comment]
这个改完以后再关闭吧

**Comment by chenbiao823** [comment]
金币显示条可以考虑再往右边移一小段距离，这样点开升级窗口就很清楚了。目前会覆盖一点金币的标识。

**Comment by dracoplay** [comment]
只能再往右移动一点, 其实影响不大 因为那个位置肯定知道是金币的
