### ISSUE TITLE
[画面]游戏背景颜色和NPC颜色有点相近

### ISSUE THREAD

**Issue by chenbiao823** [GoodGameStudio/bzdxr#3]
建议把背景颜色调深，怎么样？

**Comment by dracoplay** [comment]
我跟美术沟通下

**Comment by chenbiao823** [comment]
更新后感觉比之前好了。不过我比较偏好深背景+浅NPC，感觉这样对比更明显，NPC更突出，个人意见。你觉得呢？

**Comment by dracoplay** [comment]
赞同 这个美术比较没经验 每个元素都是我教她要什么效果怎么做 这个背景也跟他提过很多次了
