### ISSUE TITLE
[界面]NPC下方的文字颜色、字体

### ISSUE THREAD

**Issue by chenbiao823** [GoodGameStudio/bzdxr#6]
目前是白色，由于背景颜色改淡化了，所以和白色有点相近，建议改深一些。另外字体也可以考虑优化一下。

**Comment by dracoplay** [comment]
颜色会再跟美术沟通 字体暂时没法改 因为中文字太多了没法全部用图片 不像英文只要26个字母

**Comment by chenbiao823** [comment]
请教一下，游戏编程中，中文字体只有一种吗？

**Comment by dracoplay** [comment]
系统有的字体就能用, 但是不同系统经常支持的字体不一样
