### ISSUE TITLE
[战斗]Boss战时感觉触屏不是很灵敏

### ISSUE THREAD

**Issue by chenbiao823** [GoodGameStudio/bzdxr#8]
设备：iOS
情况：普通战斗时没有察觉，Boss战时感觉第一时间点击后都没有反应（两种战斗模式都是这样），点击好几次后才有该有的打击效果。之前的版本没有遇到这个情况。

**Comment by dracoplay** [comment]
测试的设备及iOS版本是多少 我在6上和iPad air上测试是好的

**Comment by chenbiao823** [comment]
8.3
设备iPhone 5c
